apiVersion: v1
kind: Service
metadata:
  name: hellojava-svc
spec:
  type: ClusterIP
  ports:
   - name: "http-port"
     protocol: "TCP"
     port: 8080
     targetPort: 8080
  selector:
    name: hellojava
